name:    fakie
version: "1.0.0"

dependencies:

- aeson
- async
- base >=4.9.1.0 && <5
- bytestring
- casing
- case-insensitive
- containers
- directory
- filepath
- text
- template-haskell
- time
- transformers
- http-client-tls
- http-client
- http-conduit
- http-types
- unordered-containers
- uri-encode
- vector
- safe-exceptions
- errors
- optparse-applicative
- network-uri
- pretty-simple
- mtl
- monad-logger
- lens
- lens-aeson
- warp
- wai
- wai-extra
- wai-transformers
- wai-app-static
- wai-util
- wai-cors
- yaml

default-extensions:
  - OverloadedStrings
  - NoImplicitPrelude
  - PatternSynonyms
  - ScopedTypeVariables
  - TemplateHaskell

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  ghc-options:
   - -Wall
   - -fwarn-tabs
   - -O2

# Runnable executable for our application
executables:
  fakie:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fakie

# Test suite
tests:
  fakie-test:
    main: Main.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - fakie
    - hspec >=2.0.0
    - microlens
    - hedgehog
    - raw-strings-qq
    - exceptions
