name:    fakie
version: "0.0.0"

dependencies:

- aeson
- base >=4.9.1.0 && <5
- bytestring
- casing
- containers
- directory
- filepath
- persistent
- persistent-sqlite
- text
- template-haskell
- time
- transformers
- http-client-tls
- http-conduit
- http-types
- unordered-containers
- vector
- safe-exceptions
- errors
- pretty-simple
- req >= 3.1.0
- req-conduit
- modern-uri
- warp
- wai
- wai-extra
- yaml

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  ghc-options:
   - -Wall
   - -fwarn-tabs
   - -O2

# Runnable executable for our application
executables:
  fakie:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fakie

# Test suite
tests:
  fakie-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - fakie
    - hspec >=2.0.0
    - microlens
